# stolen from: https://raw.githubusercontent.com/argenos/nldates-obsidian/master/.github/workflows/release.yml
name: Build obsidian plugin

on:
  push

env:
  PLUGIN_NAME: obsidian-metadump # Change this to the name of your plugin-id folder

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
    - name: Use Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: '22.x' # You might need to adjust this value to your own version
    - name: Build
      id: build
      run: |
        npm install
        npm run build --if-present
        mkdir ${{ env.PLUGIN_NAME }}
        cp main.js manifest.json ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
        ls
        echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT

    - name: Create Release and Upload Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "release_${{ github.ref }}" \
          "${{ env.PLUGIN_NAME }}.zip#${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip" \
          main.js \
          manifest.json \
          --title "Compilation for ${{ github.ref }}" \
          --draft \
          --repo ${{ github.repository }}
    # - name: Upload styles.css
    #   id: upload-css
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} 
    #     asset_path: ./styles.css
    #     asset_name: styles.css
    #     asset_content_type: text/css
